# Generated by Django 4.2.7 on 2023-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmforms',
            name='device_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
