# Generated by Django 4.2.7 on 2023-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_alter_pmforms_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmforms',
            name='staff_id',
            field=models.CharField(default='', max_length=70),
        ),
    ]
