# Generated by Django 4.2.7 on 2023-11-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_pmforms_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmforms',
            name='kgn_tag',
            field=models.CharField(default='', max_length=70),
        ),
    ]
